### PR TITLE
Backend optimisations

### PR DESCRIPTION
**Pull request by AlexFreik**
deleted some unused dependencies so julia precompiles faster

### CODE REVIEW

**Comment by AlexFreik** [comment]
deleted some unused dependancies so julia precompiles faster

**Comment by roman-timo** [comment]
I think we can make using CSV, DataFrames, JSON3, Statistics - default import. Anytime I restart Atlas I have to import them again.
I would also add some standard libraries like LinearAlgebra and DifferencialEquations as a default import.
?

**Review by roman-timo — CHANGES_REQUESTED** [review]
add default using CSV, JSON3, DataFrames, Statistics (?)

**Comment by AlexFreik** [comment]
> I think we can make using CSV, DataFrames, JSON3, Statistics - default import. Anytime I restart Atlas I have to import them again. I would also add some standard libraries like LinearAlgebra and DifferencialEquations as a default import. ?



> I think we can make using CSV, DataFrames, JSON3, Statistics - default import. Anytime I restart Atlas I have to import them again. I would also add some standard libraries like LinearAlgebra and DifferencialEquations as a default import. ?

not everyone needs them as default, since they are not added in julia as default. But we can add an template graph, with blocks where this packages already added

**Comment by AlexFreik** [comment]
Screenshot 2022-07-05 at 08 13 40
Also because of this overhead i need to wait 14 freaking minutes to build backend from fresh

**Review by roman-timo — APPROVED** [review]
Ok

**Pull request merged**
